#!/bin/sh -e

if [ "${PWD##*/}" != 'docs' ]; then
  echo "Execute this script from the 'docs' directory (see package.json)."
  exit 1
fi

function check_plantuml_deps() {
  command -v dot >/dev/null 2>&1 || { echo "Install graphviz (on mac: brew install graphviz)" >&2; exit 1; }
  command -v dot >/dev/null 2>&1 || { echo "Install plantuml (on mac: brew install plantuml)" >&2; exit 1; }
}

function generate_diagrams() {
  plantuml -r "diagrams/**.puml"
}

function install_adr_template() {
  local destdir=node_modules/adr-tools/build/main/lib/templates
  local old=${destdir}/en.md
  local new=../lib/adr_template.md

  if [ ! -f "$new" ]; then
    echo "Template $new not found"
  fi

  mv $old ${old}.bak
  cp $new ${destdir}/en.md
}

function generate_toc() {
  local input_dir=$1 header=$2 bullet=$3
  local files=`find $input_dir -maxdepth 1 -name "*.md" | awk '!/README.md/ && !/_sidebar.md/' | sort` 

  output="$header"

  IFS=$'\n'
  for file in $files
  do
    pretty=${file%.*}
    pretty=${pretty//_/\ }
    pretty=${pretty//-/\ }
    pretty=${pretty##*/}
    output="$output$bullet [$pretty]($file)\n"
  done

  echo "$output"
}

generate_all_toc() {
  # Main page for ADR
  generate_toc "adr" "<!--- Autogenerated -->\n\n # 9. Architecture Decisions\n\n" "-" > 09._Architecture_Decisions.md 
  local adr=`generate_toc adr "" "  -"`

  # Sidebar
  generate_toc . "" "-" > _sidebar.md
  insertAfter _sidebar.md "09" "$adr"

  # Table of Contents (used for PDF)
  local tocfile=00._Table_of_Contents.md
  generate_toc . "# Table of Contents\n\n" "-" > $tocfile
  insertAfter $tocfile "09" "$adr"
  awk '!/00/' < $tocfile > temp.md && mv temp.md $tocfile

  echo "Generated Table of Contents"
}

function insertAfter(){ # file line newText
  local file="$1" line="$2" newText="$3"

  if [[ -z "$newText" || "z$newText" == "z''" ]]; then 
    return 0
  fi

  newText=`echo "$newText" |  awk -v ORS='\\\n' '1'`

  awk "/$line/{print;printf \"%s\", \"$newText\";next}1" $file > tmp && mv tmp $file 
}

case $1 in
  "diagrams" )
    check_plantuml_deps
    generate_diagrams
    ;;
  "toc" )
    generate_all_toc
    ;;
  "install_adr_template" )
    install_adr_template
    ;;
  "all" )
    check_plantuml_deps
    generate_diagrams
    generate_all_toc
    ;;
esac
